#ifndef LIBJETBEEP_H
#define LIBJETBEEP_H

#ifdef __cplusplus
extern "C" {
#endif

#include "c-binding/autodevice.h"
#include "c-binding/easypay_backend.h"

#define JETBEEP_NO_ERROR 0
#define JETBEEP_ERROR_INVALID_STATE 1
#define JETBEEP_ERROR_IO 2
#define JETBEEP_ERROR_PAYMENT_NETWORK 100
#define JETBEEP_ERROR_PAYMENT_TIMEOUT 101
#define JETBEEP_ERROR_PAYMENT_SERVER 102
#define JETBEEP_ERROR_PAYMENT_SECURITY 103
#define JETBEEP_ERROR_PAYMENT_WITHDRAWAL 104
#define JETBEEP_ERROR_PAYMENT_DISCARDED 105
#define JETBEEP_ERROR_PAYMENT_UNKNOWN 106
#define JETBEEP_ERROR_PAYMENT_INVALID_PIN 107

#define JETBEEP_STATE_INVALID 0
#define JETBEEP_STATE_FIRMWARE_VERSION_NOT_SUPPORTED 1
#define JETBEEP_STATE_SESSION_OPENED 2
#define JETBEEP_STATE_SESSION_CLOSED 3
#define JETBEEP_STATE_WAITING_FOR_BARCODES 4
#define JETBEEP_STATE_WAITING_FOR_PAYMENT_RESULT 5
#define JETBEEP_STATE_WAITING_FOR_CONFIRMATION 6
#define JETBEEP_STATE_WAITING_FOR_PAYMENT_TOKEN 7


#ifdef __cplusplus
}
#endif

#endif
