/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jetbeep_JetBeep */

#ifndef _Included_com_jetbeep_JetBeep
#define _Included_com_jetbeep_JetBeep
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jetbeep_JetBeep
 * Method:    test
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_jetbeep_JetBeep_test
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
